name: Build Angular Website

on:
  push:
    branches:
      - 'master'

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build website
        working-directory: ./
        run: npm install && npm run build:prod