name: Build Angular Website

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: NG Build
        run: ng build --base-href=/portfolio/